version: '3'

services:
  gateway:
    container_name: starwars-gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"
  
  characters:
    container_name: starwars-characters
    restart: always
    build: ./characters
    ports:
      - "8001:8001"
  
  films:
    container_name: starwars-films
    restart: always
    build: ./films
    ports:
      - "8002:8002"
  
  planets:
    container_name: starwars-planets
    restart: always
    build: ./planets
    ports:
      - "8003:8003"
    
  database:
    container_name: starwars-database
    restart: always
    build: ./database
    ports:
      - "8004:8004"


